CREATE TYPE "perfil_aprendizaje_enum" AS ENUM (
	'Visual',
	'Auditivo',
	'Lector',
	'Kinestesico'
);

CREATE TYPE "nivel_enum" AS ENUM (
	'Primaria',
	'Secundaria',
	'Pregrado',
	'Posgrado'
);

CREATE TYPE "tipo_sesion_enum" AS ENUM (
	'Clase teorica',
	'Taller practico',
	'Sesion de repaso',
	'Evaluacion formativa',
	'Sesion de integracion'
);

CREATE TYPE "modalidad_enum" AS ENUM (
	'Presencial',
	'Hibrida',
	'Virtual sincronica',
	'Virtual asincronica'
);

CREATE TYPE "resultado_taxonomia_enum" AS ENUM (
	'Recordar',
	'Comprender',
	'Aplicar',
	'Analizar',
	'Evaluar',
	'Crear'
);

CREATE TYPE "estilo_contenido_enum" AS ENUM (
	'Formal academico',
	'Cercano y motivador',
	'Practico y directo',
	'Narrativo/Storytelling'
);

CREATE TABLE "docente" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nombre" VARCHAR(255) NOT NULL,
	"correo" VARCHAR(255) NOT NULL,
	"password" VARCHAR NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE "clase" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_formulario" INTEGER NOT NULL,
	"id_docente" INTEGER NOT NULL,
	"nombre" VARCHAR(255),
	"perfil" PERFIL_APRENDIZAJE_ENUM NOT NULL,
	"area" VARCHAR(255),
	"tema" VARCHAR(255),
	"nivel_educativo" NIVEL_ENUM,
	"duracion_estimada" INTEGER,
	"solo_informacion_proporcionada" BOOLEAN,
	"conocimientos_previos_estudiantes" TEXT,
	"tipo_sesion" TIPO_SESION_ENUM,
	"modalidad" MODALIDAD_ENUM,
	"objetivos_aprendizaje" TEXT,
	"resultado_taxonomia" RESULTADO_TAXONOMIA_ENUM,
	"recursos" VARCHAR(255),
	"aspectos_motivacionales" TEXT,
	"estilo_material" ESTILO_CONTENIDO_ENUM,
	"tipo_recursos_generar" VARCHAR(255),
	"estado" BOOLEAN,
	PRIMARY KEY("id")
);

CREATE TABLE "formulario" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"enlace" VARCHAR(255) NOT NULL,
	"cantidad_visual" INTEGER,
	"cantidad_auditivo" INTEGER,
	"cantidad_lector" INTEGER,
	"cantidad_kinestesico" INTEGER,
	"fecha_creacion" TIMESTAMP,
	"fecha_cierre" TIMESTAMP,
	"estado" BOOLEAN,
	PRIMARY KEY("id")
);

CREATE TABLE "contenido" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_clase" INTEGER NOT NULL,
	-- El tipo del recurso individual
	"tipo_recurso_generado" VARCHAR(255),
	-- Estilo markdown
	"contenido" TEXT,
	"estado" BOOLEAN,
	PRIMARY KEY("id")
);


CREATE TABLE "archivos" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_clase" INTEGER,
	"id_silabo" INTEGER,
	"filename" VARCHAR(255),
	PRIMARY KEY("id")
);

CREATE TABLE "silabo" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_docente" INTEGER,
	"nombre_curso" VARCHAR(255),
	"num_semanas" INTEGER,
	"resultados_esperados" TEXT,
	"ejes_tematicos" VARCHAR(255),
	"estado" BOOLEAN,
	PRIMARY KEY("id")
);

CREATE TABLE auditoria (
    id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_entidad INTEGER,
    nombre_entidad VARCHAR(255),
    fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "clase"
ADD FOREIGN KEY("id_formulario") REFERENCES "formulario"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "docente"
ADD FOREIGN KEY("id") REFERENCES "clase"("id_docente")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "clase"
ADD FOREIGN KEY("id") REFERENCES "contenido"("id_clase")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "docente"
ADD FOREIGN KEY("id") REFERENCES "silabo"("id_docente")
ON UPDATE NO ACTION ON DELETE NO ACTION;